#!/usr/bin/env sh

echo "🔍 Running lint..."
yarn lint || exit 1

echo "🧪 Running tests..."
yarn test:server --watchAll=false --coverage || exit 1
yarn test:client --watchAll=false --coverage || exit 1

echo "🏗️  Running build..."
yarn build || exit 1

echo "✅ All checks passed! Pushing to remote..."

