#!/usr/bin/env sh

echo "🔍 Running lint..."
yarn lint || exit 1

echo "🧪 Running tests..."
yarn test:ci || exit 1

echo "🏗️  Running build..."
yarn build || exit 1

echo "✅ All checks passed! Pushing to remote..."

